### ISSUE TITLE
Nonzero Decimals under Number.MIN_VALUE are treated as zero

### ISSUE THREAD

**Issue by dan-simon** [antimatter-dimensions/notations#12]
This is (I believe) due to formatUnder1000 being called and the Decimals being converted to number. It's only apparent for hex notation; on the demos page, 1e-324 isn't formatted as 80000000, but 1e-325 is formatted as 80000000. However, `(new ADNotations.HexNotation()).formatDecimal(new Decimal('1e-325'))` isn't 80000000. (It seems to me that in scientific notation, sufficiently small numbers should perhaps be formatted with negative exponents, contrary to what currently appears to be the case; however, that should probably be a separate issue.)

I don't want to try to fix this until I know whether it's considered important enough to fix and whether other notations that can use negative exponents (mostly scientific and its close relatives, but also logarithm and arguably brackets and roman) should also format small numbers differently.

**Comment by razenpok** [comment]
Looks like a legit problem for me.
I'd say we need to adjust a condition here: https://github.com/antimatter-dimensions/notations/blob/master/src/notation.ts#L15
and fix other notations when/if complaints arise.

**Comment by razenpok** [comment]
@dan-simon are you up for taking this one?

**Comment by dan-simon** [comment]
Fixed by #44 .
