### ISSUE TITLE
Wrong notation output

### ISSUE THREAD

**Issue by F1e308** [antimatter-dimensions/notations#41]
I enter ee6,mixed scientific is display 1.00e1.000e6
But I play antimatter dimensions,it display 1.00e1.000 M
![Screenshot_20191203-154145_Samsung Internet](https://user-images.githubusercontent.com/54700438/70030327-f4f9ea00-15e3-11ea-9c99-9c1a31e05dda.jpg)

**Comment by 1e1000000** [comment]
![Screenshot_20191203-155028_Samsung Internet](https://user-images.githubusercontent.com/54700438/70030844-ff68b380-15e4-11ea-9f9f-09dc2d0dbb47.jpg)

**Comment by dan-simon** [comment]
Fixed by #44 .
