### ISSUE TITLE
Number can get -ee308 but can't get ee308

### ISSUE THREAD

**Issue by F1e308** [antimatter-dimensions/notations#42]
Positive:
![Screenshot_20191203-155339_Samsung Internet](https://user-images.githubusercontent.com/54700438/70031071-6edea300-15e5-11ea-9c93-c073c9a8d980.jpg)
Negative:
![Screenshot_20191203-155429_Samsung Internet](https://user-images.githubusercontent.com/54700438/70031076-743bed80-15e5-11ea-9474-7acdedcc2387.jpg)

**Comment by dan-simon** [comment]
Fixed by #44 .
